export var ArkDynmapServer = "http://159.89.228.152";
export var ArkDynmapApiServer = "http://159.89.228.152:11000/api/players/";
export let GetPlayerDataTimer = 30; // Seconds
export var ShowPlayers = true;
export var ShowBases = true;
export var ShowTraps = true;
export var ShowBeds = true;
export var ShowTekTeleporters = true;
export var ActiveServers = [ 'Aberration', 'Extinction', 'Fjordur', 'Genesis2', 'LostIsland', 'ScorchedEarth', 'TheIsland' ];
